/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiButton: typeof import('./../components/ui/button/Button.vue')['default']
    UiInput: typeof import('./../components/ui/input/Input.vue')['default']
    UiSeparator: typeof import('./../components/ui/separator/Separator.vue')['default']
    UiSheet: typeof import('./../components/ui/sheet/Sheet.vue')['default']
    UiSheetClose: typeof import('./../components/ui/sheet/SheetClose.vue')['default']
    UiSheetContent: typeof import('./../components/ui/sheet/SheetContent.vue')['default']
    UiSheetDescription: typeof import('./../components/ui/sheet/SheetDescription.vue')['default']
    UiSheetFooter: typeof import('./../components/ui/sheet/SheetFooter.vue')['default']
    UiSheetHeader: typeof import('./../components/ui/sheet/SheetHeader.vue')['default']
    UiSheetOverlay: typeof import('./../components/ui/sheet/SheetOverlay.vue')['default']
    UiSheetTitle: typeof import('./../components/ui/sheet/SheetTitle.vue')['default']
    UiSheetTrigger: typeof import('./../components/ui/sheet/SheetTrigger.vue')['default']
    UiSidebar: typeof import('./../components/ui/sidebar/Sidebar.vue')['default']
    UiSidebarContent: typeof import('./../components/ui/sidebar/SidebarContent.vue')['default']
    UiSidebarFooter: typeof import('./../components/ui/sidebar/SidebarFooter.vue')['default']
    UiSidebarGroup: typeof import('./../components/ui/sidebar/SidebarGroup.vue')['default']
    UiSidebarGroupAction: typeof import('./../components/ui/sidebar/SidebarGroupAction.vue')['default']
    UiSidebarGroupContent: typeof import('./../components/ui/sidebar/SidebarGroupContent.vue')['default']
    UiSidebarGroupLabel: typeof import('./../components/ui/sidebar/SidebarGroupLabel.vue')['default']
    UiSidebarHeader: typeof import('./../components/ui/sidebar/SidebarHeader.vue')['default']
    UiSidebarInput: typeof import('./../components/ui/sidebar/SidebarInput.vue')['default']
    UiSidebarInset: typeof import('./../components/ui/sidebar/SidebarInset.vue')['default']
    UiSidebarMenu: typeof import('./../components/ui/sidebar/SidebarMenu.vue')['default']
    UiSidebarMenuAction: typeof import('./../components/ui/sidebar/SidebarMenuAction.vue')['default']
    UiSidebarMenuBadge: typeof import('./../components/ui/sidebar/SidebarMenuBadge.vue')['default']
    UiSidebarMenuButton: typeof import('./../components/ui/sidebar/SidebarMenuButton.vue')['default']
    UiSidebarMenuButtonChild: typeof import('./../components/ui/sidebar/SidebarMenuButtonChild.vue')['default']
    UiSidebarMenuItem: typeof import('./../components/ui/sidebar/SidebarMenuItem.vue')['default']
    UiSidebarMenuSkeleton: typeof import('./../components/ui/sidebar/SidebarMenuSkeleton.vue')['default']
    UiSidebarMenuSub: typeof import('./../components/ui/sidebar/SidebarMenuSub.vue')['default']
    UiSidebarMenuSubButton: typeof import('./../components/ui/sidebar/SidebarMenuSubButton.vue')['default']
    UiSidebarMenuSubItem: typeof import('./../components/ui/sidebar/SidebarMenuSubItem.vue')['default']
    UiSidebarProvider: typeof import('./../components/ui/sidebar/SidebarProvider.vue')['default']
    UiSidebarRail: typeof import('./../components/ui/sidebar/SidebarRail.vue')['default']
    UiSidebarSeparator: typeof import('./../components/ui/sidebar/SidebarSeparator.vue')['default']
    UiSidebarTrigger: typeof import('./../components/ui/sidebar/SidebarTrigger.vue')['default']
    UiSkeleton: typeof import('./../components/ui/skeleton/Skeleton.vue')['default']
    UiTooltip: typeof import('./../components/ui/tooltip/Tooltip.vue')['default']
    UiTooltipContent: typeof import('./../components/ui/tooltip/TooltipContent.vue')['default']
    UiTooltipProvider: typeof import('./../components/ui/tooltip/TooltipProvider.vue')['default']
    UiTooltipTrigger: typeof import('./../components/ui/tooltip/TooltipTrigger.vue')['default']
  }
}
